//data.js
var DATA = [
	{name:"工",key:"A",keyCode:65},
	{name:"匚",key:"A",keyCode:65},
	{name:"艹",key:"A",keyCode:65},
	{name:"廾",key:"A",keyCode:65},
	{name:"廿",key:"A",keyCode:65},
	//{name:"共头",key:"A",keyCode:65},
	{name:"七",key:"A",keyCode:65},
	{name:"弋",key:"A",keyCode:65},
	{name:"戈",key:"A",keyCode:65},

	{name:"子",key:"B",keyCode:66},
	{name:"孑",key:"B",keyCode:66},
	{name:"了",key:"B",keyCode:66},
	{name:"巜",key:"B",keyCode:66},
	{name:"也",key:"B",keyCode:66},
	{name:"凵",key:"B",keyCode:66},
	{name:"耳",key:"B",keyCode:66},
	{name:"阝",key:"B",keyCode:66},
	{name:"卩",key:"B",keyCode:66},
	{name:"⺋",key:"B",keyCode:66},

	{name:"又",key:"C",keyCode:67},
	//{name:"颈头",key:"C",keyCode:67},
	//{name:"予头",key:"C",keyCode:67},
	{name:"厶",key:"C",keyCode:67},
	{name:"巴",key:"C",keyCode:67},
	{name:"马",key:"C",keyCode:67},

	{name:"大",key:"D",keyCode:68},
	{name:"犬",key:"D",keyCode:68},
	{name:"古",key:"D",keyCode:68},
	{name:"石",key:"D",keyCode:68},
	{name:"三",key:"D",keyCode:68},
	//{name:"羊身子",key:"D",keyCode:68},
	//{name:"着身子",key:"D",keyCode:68},
	{name:"镸",key:"D",keyCode:68},
	{name:"厂",key:"D",keyCode:68},
	{name:"丆",key:"D",keyCode:68},
	//{name:"右头",key:"D",keyCode:68},
	//{name:"犬头",key:"D",keyCode:68},

	{name:"月",key:"E",keyCode:69},
	//{name:"月身",key:"E",keyCode:69},
	//{name:"舟身",key:"E",keyCode:69},
	{name:"用",key:"E",keyCode:69},
	{name:"彡",key:"E",keyCode:69},
	//{name:"采头",key:"E",keyCode:69},
	{name:"乃",key:"E",keyCode:69},
	//{name:"衣底",key:"E",keyCode:69},
	{name:"豕",key:"E",keyCode:69},
	//{name:"衣底2",key:"E",keyCode:69},
	//{name:"犬字旁",key:"E",keyCode:69},
	{name:"豸",key:"E",keyCode:69},

	{name:"土",key:"F",keyCode:70},
	{name:"士",key:"F",keyCode:70},
	{name:"二",key:"F",keyCode:70},
	{name:"干",key:"F",keyCode:70},
	{name:"十",key:"F",keyCode:70},
	{name:"寸",key:"F",keyCode:70},
	{name:"雨",key:"F",keyCode:70},
	//{name:"贵字头",key:"F",keyCode:70},

	{name:"王",key:"G",keyCode:71},
	{name:"",key:"G",keyCode:71},
	{name:"五",key:"G",keyCode:71},
	{name:"一",key:"G",keyCode:71},
	{name:"戋",key:"G",keyCode:71},

	{name:"目",key:"H",keyCode:72},
	//{name:"具头",key:"H",keyCode:72},
	{name:"丨",key:"H",keyCode:72},
	{name:"卜",key:"H",keyCode:72},
	//{name:"止头",key:"H",keyCode:72},
	{name:"虍",key:"H",keyCode:72},
	{name:"上",key:"H",keyCode:72},
	{name:"止",key:"H",keyCode:72},
	//{name:"足底",key:"H",keyCode:72},
	//{name:"皮头",key:"H",keyCode:72},

	{name:"水",key:"I",keyCode:73},
	{name:"氺",key:"I",keyCode:73},
	//{name:"水手",key:"I",keyCode:73},
	{name:"氵",key:"I",keyCode:73},
	//{name:"兴头",key:"I",keyCode:73},
	//{name:"兴头2",key:"I",keyCode:73},
	{name:"小",key:"I",keyCode:73},
	{name:"⺌",key:"I",keyCode:73},

	{name:"日",key:"J",keyCode:74},
	{name:"曰",key:"J",keyCode:74},
	//{name:"躺日",key:"J",keyCode:74},
	{name:"早",key:"J",keyCode:74},
	{name:"刂",key:"J",keyCode:74},
	//{name:"两丨",key:"J",keyCode:74},
	//{name:"师旁",key:"J",keyCode:74},
	//{name:"川左2",key:"J",keyCode:74},
	{name:"虫",key:"J",keyCode:74},

	{name:"口",key:"K",keyCode:75},
	//{name:"三竖",key:"K",keyCode:75},
	{name:"川",key:"K",keyCode:75},

	{name:"田",key:"L",keyCode:76},
	{name:"甲",key:"L",keyCode:76},
	{name:"囗",key:"L",keyCode:76},
	{name:"四",key:"L",keyCode:76},
	{name:"罒",key:"L",keyCode:76},
	//{name:"曾中",key:"L",keyCode:76},
	{name:"皿",key:"L",keyCode:76},
	{name:"车",key:"L",keyCode:76},
	{name:"力",key:"L",keyCode:76},

	{name:"山",key:"M",keyCode:77},
	{name:"由",key:"M",keyCode:77},
	{name:"贝",key:"M",keyCode:77},
	{name:"冂",key:"M",keyCode:77},
	//{name:"骨头",key:"M",keyCode:77},
	{name:"几",key:"M",keyCode:77},

	{name:"已",key:"N",keyCode:78},
	{name:"己",key:"N",keyCode:78},
	{name:"巳",key:"N",keyCode:78},
	{name:"乙",key:"N",keyCode:78},
	{name:"尸",key:"N",keyCode:78},
	{name:"羽",key:"N",keyCode:78},
	//{name:"左匡",key:"N",keyCode:78},
	//{name:"眉头",key:"N",keyCode:78},
	{name:"忄",key:"N",keyCode:78},
	//{name:"小多点",key:"N",keyCode:78},
	{name:"心",key:"N",keyCode:78},

	{name:"火",key:"O",keyCode:79},
	{name:"业",key:"O",keyCode:79},
	{name:"灬",key:"O",keyCode:79},
	{name:"米",key:"O",keyCode:79},
	//{name:"业头",key:"O",keyCode:79},
	//{name:"亦尾",key:"O",keyCode:79},

	{name:"之",key:"P",keyCode:80},
	{name:"辶",key:"P",keyCode:80},
	{name:"廴",key:"P",keyCode:80},
	{name:"冖",key:"P",keyCode:80},
	{name:"宀",key:"P",keyCode:80},
	//{name:"礻缺少点",key:"P",keyCode:80},

	{name:"金",key:"Q",keyCode:81},
	{name:"钅",key:"Q",keyCode:81},
	{name:"勹",key:"Q",keyCode:81},
	{name:"夕",key:"Q",keyCode:81},
	{name:"乂",key:"Q",keyCode:81},
	//{name:"犭少一撇",key:"Q",keyCode:81},
	//{name:"流底",key:"Q",keyCode:81},
	//{name:"鱼无尾",key:"Q",keyCode:81},
	{name:"儿",key:"Q",keyCode:81},
	//{name:"夕无点",key:"Q",keyCode:81},
	//{name:"夕多点",key:"Q",keyCode:81},
	//{name:"氏无七",key:"Q",keyCode:81},

	{name:"白",key:"R",keyCode:82},
	{name:"手",key:"R",keyCode:82},
	//{name:"看头",key:"R",keyCode:82},
	{name:"扌",key:"R",keyCode:82},
	//{name:"左两点",key:"R",keyCode:82},
	//{name:"矢无人",key:"R",keyCode:82},
	{name:"斤",key:"R",keyCode:82},
	//{name:"斤偏旁",key:"R",keyCode:82},
	{name:"⺁",key:"R",keyCode:82},

	{name:"木",key:"S",keyCode:83},
	{name:"丁",key:"S",keyCode:83},
	{name:"西",key:"S",keyCode:83},

	{name:"禾",key:"T",keyCode:84},
	//{name:"禾苗旁",key:"T",keyCode:84},
	{name:"竹",key:"T",keyCode:84},
	//{name:"⺮",key:"T",keyCode:84},
	{name:"丿",key:"T",keyCode:84},
	{name:"彳",key:"T",keyCode:84},
	{name:"攵",key:"T",keyCode:84},
	{name:"夂",key:"T",keyCode:84},
	//{name:"矢无大",key:"T",keyCode:84},

	{name:"立",key:"U",keyCode:85},
	{name:"六",key:"U",keyCode:85},
	//{name:"立头",key:"U",keyCode:85},
	{name:"辛",key:"U",keyCode:85},
	{name:"冫",key:"U",keyCode:85},
	{name:"丬",key:"U",keyCode:85},
	{name:"疒",key:"U",keyCode:85},
	{name:"门",key:"U",keyCode:85},
	//{name:"立底",key:"U",keyCode:85},
	//{name:"立身",key:"U",keyCode:85},

	{name:"女",key:"V",keyCode:86},
	{name:"刀",key:"V",keyCode:86},
	{name:"九",key:"V",keyCode:86},
	{name:"巛",key:"V",keyCode:86},
	{name:"臼",key:"V",keyCode:86},
	{name:"彐",key:"V",keyCode:86},

	{name:"人",key:"W",keyCode:87},
	{name:"亻",key:"W",keyCode:87},
	{name:"八",key:"W",keyCode:87},
	{name:"癶",key:"W",keyCode:87},
	//{name:"祭头",key:"W",keyCode:87},

	{name:"纟",key:"X",keyCode:88},
	//{name:"纟无横",key:"X",keyCode:88},
	{name:"幺",key:"X",keyCode:88},
	//{name:"母无心",key:"X",keyCode:88},
	{name:"弓",key:"X",keyCode:88},
	{name:"匕",key:"X",keyCode:88},
	//{name:"比左",key:"X",keyCode:88},

	{name:"言",key:"Y",keyCode:89},
	{name:"訁",key:"Y",keyCode:89},
	{name:"讠",key:"Y",keyCode:89},
	{name:"文",key:"Y",keyCode:89},
	{name:"方",key:"Y",keyCode:89},
	{name:"丶",key:"Y",keyCode:89},
	{name:"亠",key:"Y",keyCode:89},
	//{name:"高头2",key:"Y",keyCode:89},
	{name:"广",key:"Y",keyCode:89},
	{name:"圭",key:"Y",keyCode:89},

	{name:"Z",key:"Z",keyCode:90}
]